linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - containedctx
  - copyloopvar
  - cyclop
  - depguard
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - err113
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exptostd
  - fatcontext
  - forcetypeassert
  - gocheckcompilerdirectives
  - gochecknoglobals
  - gochecknoinits
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - godot
  - godox
  - gofmt
  - gofumpt
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - iface
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - intrange
  - ireturn
  - lll
  - loggercheck
  - maintidx
  - mirror          # Not sure what this is
  - misspell
  - mnd             # Update `linters-settings.mnd.ignored-numbers` with things to ignore
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilnesserr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - paralleltest
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - recvcheck
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tagliatelle
  - tenv
  - testableexamples
  - testifylint
  - testpackage
  - thelper
  - tparallel
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - usetesting
  - varnamelen
  - wastedassign
  - whitespace
  - wrapcheck
  - zerologlint
  # Disabled
  # ========
  # - decorder        # Personal preference
  # - exhaustruct     # Zero values should be useful
  # - forbidigo       # Not necessary; defaults aren't useful here
  # - funlen          # Already using cyclop
  # - gci             # Other linters handle imports already
  # - ginkgolinter    # Not using ginkgo or gomega
  # - gocyclo         # Already using cyclop
  # - goheader        # Not necessary; no standard file header
  # - goimports       # Doesn't work if `diff` isn't present (Windows)
  # - gomoddirectives # Not realy using module directives (goal is to minimize non-stdlib imports)
  # - gomodguard      # Not needed, goal is to minimize non-stdlib imports
  # - makezero        # If I'm calling make() it is because I want a non-zero initial size
  # - nlreturn        # Personal preference
  # - wsl             # Personal preference

linters-settings:
  depguard:
    rules:
      main:
        allow:
        - "$gostd"
        - github.com/tvarney/consterr
        - github.com/stretchr/testify